# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-15 14:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0012_auto_20170609_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='diagram_image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=b'categories', verbose_name='Diagram'),
        ),
    ]
