# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-25 19:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0013_category_diagram_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReplacementProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Determines order of the products. A product with a higher value will appear before one with a lower ranking.', verbose_name='order')),
            ],
            options={
                'ordering': ['primary', '-order'],
                'abstract': False,
                'verbose_name_plural': 'Replacement products',
                'verbose_name': 'Replacement Product',
            },
        ),
        migrations.AlterField(
            model_name='category',
            name='diagram_image',
            field=models.ImageField(blank=True, help_text='Parts Diagram. Only upload a diagram image if you are creating a Leaf Category (Component).', max_length=255, null=True, upload_to=b'categories', verbose_name='Diagram'),
        ),
        migrations.AlterField(
            model_name='product',
            name='recommended_products',
            field=models.ManyToManyField(blank=True, help_text='These are products that are recommended to accompany the main product.', related_name='recommendations', through='catalogue.ProductRecommendation', to='catalogue.Product', verbose_name='Recommended products'),
        ),
        migrations.AddField(
            model_name='replacementproduct',
            name='primary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='primary_replacement', to='catalogue.Product', verbose_name='Primary product'),
        ),
        migrations.AddField(
            model_name='replacementproduct',
            name='replacement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.Product', verbose_name='Replacement product'),
        ),
        migrations.AddField(
            model_name='product',
            name='replacement_products',
            field=models.ManyToManyField(blank=True, help_text='These are products that are designated to replace main product.', related_name='replacements', through='catalogue.ReplacementProduct', to='catalogue.Product', verbose_name='Replacement products'),
        ),
        migrations.AlterUniqueTogether(
            name='replacementproduct',
            unique_together=set([('primary', 'replacement')]),
        ),
    ]
