# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-12 19:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0014_auto_20180125_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='diagram_number',
            field=models.CharField(blank=True, help_text='Number associated with part diagram.', max_length=5, null=True, verbose_name='Diagram number'),
        ),
    ]
