# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-10 14:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0017_auto_20180402_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='diagram_number',
            field=models.CharField(blank=True, help_text='Number associated with part diagram.', max_length=8, null=True, verbose_name='Diagram number'),
        ),
    ]
