# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-02 20:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marine_parts', '0002_auto_20171102_2017'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='joined',
            new_name='created',
        ),
    ]
