# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-02 20:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marine_parts', '0003_auto_20171102_2018'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='created',
            new_name='date_joined',
        ),
    ]
